# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8177e1edd3f9a72571eb71076b56ef913607dab201e2fec46496fb1fd39a0559d89ca2a39a4d69facdab47cce6e08834cdb18250d13d08047f0023ac21496ea

test:
  secret_key_base: 65a6b6944ab28f66fc4670529d93328b97db6f83fe9d9095adf2b996542c07c09275cb15e9f00bc24cfecd6c6fd68067158d461c51b5371659afa6b67aeb39d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
